title:            coldmochi
description:      ...more like a code monkey :)
author :
  name : Terry Ma
  email : zhenchuan.ma@gmail.com
  github : terryma
  twitter : terry_ma
  feedburner : terryma
url:              http://coldmochi.com
signoff:          terry
disqus_shortname: coldmochi
facebook_admin: 240596299303664
facebook_appid: 171306593039270
google_analytics: UA-16954188-3

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         GitHub
    url:          http://github.com/terryma
  - name:         LinkedIn
    url:          http://www.linkedin.com/in/terryma

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
