baseURL = "https://terry.ma/"
languageCode = "en-us"
title = "Terry Ma"
theme = "hallo"
googleAnalytics = "UA-16954188-3"

[Author]
  name = 'Terry'

[params]
  greeting = "Hello!"

  [[params.links]]
    iconset = "fas"
    icon = "envelope"
    title = "E-mail"
    url = "mailto:hi@terry.ma"

  [[params.links]]
    icon = 'github'
    title = 'Github'
    url = "https://github.com/terryma/"

  [[params.links]]
    icon = 'linkedin'
    title = 'LinkedIn'
    url = "https://www.linkedin.com/in/terryma/"
