baseURL = "http://terry.ma/"
languageCode = "en-us"
title = "Terry Ma"
theme = "minimal"
disqusShortname = "coldmochi" # delete this to disable disqus comments

[params]
    author = "Terry Ma"
    description = "❤️ code, startups, VR, bouldering, life"
    githubUsername = "#terryma"
    accent = "lightBlue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:hi@terry.ma"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/terryma/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/terryma/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://terry.ma/resume.pdf"
    name = "file-text-o"
    weight = 4
